### ISSUE TITLE
More advanced color support

### ISSUE THREAD

**Issue by notramo** [jedsoft/most#1]
[`bat`](https://github.com/sharkdp/bat) uses some advanced color escape codes, which `most` doesn't support. `less` supports it with the `--RAW-CONTROL-CHARS` option.
It can be observed with:
```bash
bat file.txt | most
```

**Comment by jedsoft** [comment]
Please perform the following:

   bat file.txt > /tmp/file.txt-bat

Then send or attach /tmp/file.txt-bat

Thanks.

**Comment by notramo** [comment]
It's a syntax highlighted version of a simple BASH Hello world script.
[bat-colored.txt](https://github.com/jedsoft/most/files/8596800/bat-colored.txt)
```
[38;5;238m───────┬────────────────────────────────────────────────────────────────────────[0m
       [38;5;238m│ [0mFile: [1mhello.sh[0m
       [38;5;238m│ [0mSize: [1m33 B[0m
[38;5;238m───────┼────────────────────────────────────────────────────────────────────────[0m
[38;5;238m   1[0m   [38;5;238m│[0m [38;2;124;120;101m#[0m[38;2;124;120;101m!/bin/bash[0m
[38;5;238m   2[0m   [38;5;238m│[0m 
[38;5;238m   3[0m   [38;5;238m│[0m [38;2;102;217;239mecho[0m[38;2;255;255;255m [0m[38;2;255;255;255m"[0m[38;2;230;219;116mHello world![0m[38;2;255;255;255m"[0m
[38;5;238m───────┴────────────────────────────────────────────────────────────────────────[0m
```

**Comment by jedsoft** [comment]
I have no problems viewing the file using the current development in a terminal that supports truecolors.

You may have to set the COLORTERM  environment variable.  See <https://gist.github.com/XVilka/8346728> for more information.

**Comment by notramo** [comment]
@jedsoft Is it a feature implemented since the latest tagged release? If this is the case, when do you plan to release a new version?
