### ISSUE TITLE
Scroll up/down one screen do not work after `b373005`

### ISSUE THREAD

**Issue by sebastiencs** [jedsoft/most#10]
Hello,

When I compile `most` on the commit https://github.com/jedsoft/most/commit/b373005f5e24e2b3be64dede515455a3f44d8c70, the 2 commands `Scroll up one screen` and `Scroll down one screen` (that I call with keyboard `SPACE`/`D`,`U`,`BACKSPACE`) do not work.
Using those commands have no effect on the view.

Using the parent commit https://github.com/jedsoft/most/commit/4c02d626e4a4465a114ac02acb7689259ad3cdf9, both commands work correctly

Please let me know if you need more informations

**Comment by jedsoft** [comment]
I am unable to reproduce this.  Please provide the output of:

   most --version 2>&1 | head

your terminal program and version, the values of the TERM and COLORTERM environment variables, as well as your OS, and if it is 32 or 64 bit.

Thanks,
--John
