### ISSUE TITLE
Web site still says 5.1.0 is the latest release

### ISSUE THREAD

**Issue by ryandesign** [jedsoft/most#24]
5.2.0 was release in 2022 (#11) but [the web site](http://www.jedsoft.org/most/download.html) still says:

> The latest released version of [most](https://www.jedsoft.org/most/) is 5.1.0 and is available from https://www.jedsoft.org/releases/most/.

**Comment by jedsoft** [comment]
Thanks for pointing that out.  I updated the web page.  --John

On Thu, 04 Apr 2024 06:05:59 +0000 (UTC), Ryan Carsten Schmidt ***@***.***> said:

**Comment by ryandesign** [comment]
Thanks!
