### ISSUE TITLE
Wrong truecolor on Alacritty

### ISSUE THREAD

**Issue by notramo** [jedsoft/most#6]
Alacritty is a GPU accelerated terminal emulator, with many cool features, including vi mode, search, and regex hints. https://alacritty.org/#About
It sets `TERM=alacritty`.
![image](https://user-images.githubusercontent.com/26059643/166194680-11b6cd26-25f9-418b-914b-e36ecb4dc24e.png)

**Comment by jumps-are-op** [comment]
try `TERM=xterm-256color`

**Comment by notramo** [comment]
Doesn't work either.

**Comment by silentnoodlemaster** [comment]
QTerminal and Kitty, don't see any pattern of when it happens

![image](https://user-images.githubusercontent.com/10667809/174561264-c172141f-b50e-4933-8d16-7bed9883c121.png)

**Comment by jedsoft** [comment]
Are you able to redirect the output from the command that you are running to a file instead of to most?  If so, please post that file here.  Thanks.

**Comment by silentnoodlemaster** [comment]
Colors got disabled if redirected, but I did `PAGER="cat -e"` and got this
[kitty-git.txt](https://github.com/jedsoft/most/files/8943525/kitty-git.txt)

**Comment by jedsoft** [comment]
Please try the latest commit to see if it addresses the problem (pre5.2.0-11).

Thanks

**Comment by silentnoodlemaster** [comment]
@jedsoft yes that solved the issue

**Comment by jedsoft** [comment]
Thanks.  I will close this issue
