### ISSUE TITLE
Issue with unicode character

### ISSUE THREAD

**Issue by MalteHei** [jedsoft/most#7]
Hello,
a file i just created with an external program contains a [ZERO WIDTH NO-BREAK SPACE](https://apps.timwhitlock.info/unicode/inspect?s=%EF%BB%BF) unicode character.
When viewing a `git diff` of this file, using most as the pager for git (`core.pager=most`), most displays some confusing control sequence (`^[[m^[[m`).
The first character following this unicode char is also swallowed, which somehow shortens the sequence (`^[[m^[`). When viewed directly via `most file` instad of `git diff`, the sequence is not displayed, but the following char is still being swallowed.

---

To reprocude:
```shell
mkdir -p /tmp/most-utf8 && cd /tmp/most-utf8
printf '\xEF\xBB\xBF' > file
printf '\n\xEF\xBB\xBFa' >> file
printf '\n\xEF\xBB\xBFabc' >> file
git init && git config core.pager most && git add . && git diff --staged
most file
```

Output of `git diff`:
```diff
diff --git a/file b/file
new file mode 100644
index 0000000..b1e4a43
--- /dev/null
+++ b/file
@@ -0,0 +1,3 @@
+^[[m^[[m
+^[[m^[
+^[[m^[bc
\ No newline at end of file
```

anf of `most`:
```


bc
```

while the file actually contains:
```
﻿
﻿a
﻿abc
```

---

`cat` and `less` render the ZERO WIDTH NO-BREAK SPACE as a normal width space, not swallowing any following characters.
I haven't looked at any other characters, but I suspect that this bug occurs with more unicode characters (especially 0 width ones).

**Comment by jedsoft** [comment]
Thanks for your excellent bug report.  I believe that the bug has been corrected in
0ab81d64713da4b9193d2c90411a16e5ba238613

**Comment by jedsoft** [comment]
I believe that this bug has been fixed.
