### ISSUE TITLE
Unexpected results when reviewing trough paru

### ISSUE THREAD

**Issue by silentnoodlemaster** [jedsoft/most#8]
issue with [paru](https://github.com/Morganamilo/paru) when installing new packages ![mostbad](https://user-images.githubusercontent.com/10667809/174021184-6cb4195f-53d8-4a1e-b1d5-1b0c96ad1d03.png)

updating existing ones works as expected: 
![mostgood](https://user-images.githubusercontent.com/10667809/174021193-2017e029-365c-4bf1-90d6-dc8a2af7c6b5.png)

**Comment by jedsoft** [comment]
The first image shows truecolor escape sequences.  What version of most are you using?
What is the output of:

   most --version 2>&1 | head
?
Thanks

**Comment by silentnoodlemaster** [comment]
`$ most --version 2>&1 | head `

MOST version 5.1.0 (S-Lang version 2.3.2)
Usage:
most [-1Cbcdkrstvw] [+/string] [+line number] [+s] [+d] file...
 where: -1:  assume VT100 terminal. (VMS only)
        -b:  Startup in binary mode.
        -C:  disable color support
        -c:  Make searches case sensitive.
        -d:  Do not display the \ wrap marker when wrapping lines.
        -M:  Do not attempt to mmap files.
        -r:  Default to regexp search

**Comment by jedsoft** [comment]
That version does not support truecolor.   Truecolor support was added in pre5.2-7.

**Comment by silentnoodlemaster** [comment]
is there a roadmap for 5.2?
